### ISSUE TITLE
Circumcision Implementation & Timing

### ISSUE THREAD

**Issue by mmcleod89** [UCL/hivpy#94]
Circumcision at birth implemented currently for entire population (born and unborn). 
Can be timed and then compared to the implementation where there are two stages: circumcision at birth for the initial population male and age > 0, and then the update circumcision at every time step. 

Can use `perf_counter` from the `time` library to time functions. 
Can time circumcision update function for multiple function calls and divide the time to get the average to get a more accurate result. 

Likely that impact on performance will be small anyway.

**Comment by pineapple-cat** [comment]
Circumcision at birth was implemented in two ways in the circumcision module:

- `init_birth_circumcision_all` - Initialises circumcision at birth for the entire male population, both born and unborn.
- `init_birth_circumcision_born` - Initialises circumcision at birth for all born males (age >= 0.25).
`update_birth_circumcision` - Updates birth circumcision for newly born males during each time step (age >= 0.25 and age - time_step < 0.25, assuming ages have already been incremented this time step).

After some functionality testing, I gathered timing data over the course of 1000 iterations. During those iterations, both initialisation functions were carried out once and updates were carried out over the course of a simulated 10 years. The results were as follows:

- Average time taken to run `init_birth_circumcision_all`: **82.971 ± 2.459 ms**
- Average time taken to run `init_birth_circumcision_born`: **1.492 ± 0.120 ms**
- Average time taken to run `update_birth_circumcision` per time step: **2.551 ± 0.537 ms** (derived from a total average of 103.530 ms for a simulated 10 years of updates)

**Comment by pineapple-cat** [comment]
Initialising birth circumcision for all males is time-consuming mostly due to circumcision date calculation. Once the male population is circumcised, the circumcision date of unborn individuals is determined by a transform on the age column. Birth circumcision updates per time step take longer than initialising birth circumcision for born males because it is necessary to find the sub-population of newly born males for each time step. Once a simulation reaches 32 time steps (a simulated ~8 years of updates, in this case), the time taken by `init_birth_circumcision_born` + `update_birth_circumcision` will exceed that of `init_birth_circumcision_all`.
